matgrp2dic = {1 :    "AMORPRC",
            2  :     "CHKVLF",
            3  :      "DIGER",
            4   :   "DISCUSS",
            5  :    "EMR-ALU",
            6  : "GENELGIDER",
            7  :      "HRVLF",
            8  :      "KNORR",
            9  :    "KNORR-D",
            10   :  "KOMPPRC",
            11 :       "SARF",
            12  : "SLDNGREED",
            13   :  "VALFPLK",
            14  :   "WABCO-D",
            15   : "WABCO-TR"}