SELECT IASWORKCENT.WORKCENTER
	FROM IASWORKCENT
	LEFT OUTER JOIN IASWORKCENX ON (IASWORKCENX.CLIENT = IASWORKCENT.CLIENT
		AND IASWORKCENX.COMPANY = IASWORKCENT.COMPANY
		AND IASWORKCENX.PLANT = IASWORKCENT.PLANT
		AND IASWORKCENX.WORKCENTER = IASWORKCENT.WORKCENTER
		AND IASWORKCENX.LANGU = 'T'
		AND IASWORKCENX.VALIDFROM <= '2024-02-14'
		AND IASWORKCENX.VALIDUNTIL >= '2024-02-14')
	WHERE IASWORKCENT.CREATEDAT > '2020-12-30 11:30:13'
		AND IASWORKCENT.WORKCENTER LIKE 'P-%'
		AND IASWORKCENT.ISDELETE = 0
		AND IASWORKCENT.USEIN = 0 ORDER BY IASWORKCENT.CREATEDAT DESC

