SELECT '' AS MPOINT,  FORMAT(IASPRDCONF.WORKSTART ,'yyyy-MM') AS DATE,
CAST(SUM(IASPRDCONF.OUTPUT +IASPRDCONF.SCRAP+IASPRDCONF.REWORK) AS INT) AS QUANTITY,
CONVERT(DECIMAL(10,3),SUM((IASPRDCONF.OUTPUT +IASPRDCONF.SCRAP+IASPRDCONF.REWORK)*B.NETWEIGHT)/1000000) AS TOTALNETWEIGHT,
0.000 AS kwhPERton
FROM IASPRDCONF
LEFT JOIN IASPRDOPR A ON  A.CONFIRMATION = IASPRDCONF.CONFIRMATION
LEFT JOIN IASMATBASIC B ON A.MATERIAL = B.MATERIAL AND B.COMPANY  = '01'
WHERE IASPRDCONF.WORKCENTER LIKE 'P-%'
AND IASPRDCONF.WORKSTART BETWEEN  'xxxx-yy-zz' AND 'aaaa-bb-cc'
GROUP BY FORMAT(IASPRDCONF.WORKSTART,'yyyy-MM')
ORDER BY DATE