SELECT COSTCENTER,SUM(OUTPUT) AS CONSUMPTION FROM VLFENERGY WHERE
MPOINT NOT LIKE CASE COSTCENTER WHEN 'CNC' THEN '%-%' ELSE '%ASDF%' END
AND MPOINT NOT LIKE CASE COSTCENTER WHEN 'PRESHANE' THEN '%-%' ELSE '%ASDF%'  END
GROUP BY COSTCENTER
