INSERT INTO VLFTOTALSTOCKHISTORY SELECT MAX(I.SKUNIT) AS SKUNIT, SUM(I.SKQUANTITY * (1 - 2 * I.QPOSTWAY)) AS TOTALSTOCK, MB.ACIKLAMA, MB.GRUBU,MB.PARCA, 'xxxx-xx-xx'  AS DATE
		FROM IASINVITEM I 
		LEFT JOIN IASMATBASIC MB ON MB.MATERIAL = I.MATERIAL AND I.COMPANY =MB.COMPANY AND I.CLIENT = MB.CLIENT
		WHERE I.CLIENT = '00' 
		AND I.COMPANY = '01' 
		AND I.PLANT LIKE '%' 
		AND I.WAREHOUSE LIKE '%' 
		AND I.STOCKPLACE LIKE '%' 
		AND I.SPECIALSTOCK LIKE '%' 
		AND I.MATERIAL LIKE '%' 
		AND I.BATCHNUM LIKE '%' 
		AND I.DOCDATE <= 'xxxx-xx-xx'
		AND I.ISCANCELED = 0 
		AND I.MATTYPE LIKE '%' 
		AND I.MATGRP LIKE '%' 
		AND I.MTEXT LIKE '%' 
        AND MB.MATTYPE NOT IN ('IBKM','BSRF')
		AND I.WAREHOUSE  NOT IN ('BKM','600','GTP','700','800')
		AND (I.WAREHOUSE != (CASE SUBSTRING(I.MATERIAL,1,3) WHEN 'OTK' THEN  '100' ELSE  'BKM'  END))
		GROUP BY  MB.ACIKLAMA, MB.GRUBU,MB.PARCA
		HAVING SUM(I.SKQUANTITY * (1 - 2 * I.QPOSTWAY)) > 0
		ORDER BY MB.ACIKLAMA, MB.GRUBU,MB.PARCA




