WITH KMR_DATA AS (
    SELECT
        'KMR-05' as MACHINE,
        CASE
            WHEN A.ICCAP < M.ICCAP2 THEN 'IK'
            WHEN A.ICCAP > (M.ICCAP2 + M.ICCAPTOL2) THEN 'IB'
            WHEN A.DISCAP < M.DISCAP2 THEN 'DK'
            WHEN A.DISCAP > (M.DISCAP2 + M.DISCAPTOL2) THEN 'DB'
            ELSE ''
        END AS NOTOKDETAIL,
        A.MATERIAL,
        A.CONFIRMATION
	FROM
        [dbo].[XYZ] A
	LEFT JOIN
    [VALFSAN604].[dbo].IASPRDORDER P ON P.PRDORDER = A.CONFIRMATION
    LEFT JOIN
        [VALFSAN604].[dbo].IASMATBASIC M ON P.MATERIAL = M.MATERIAL AND P.COMPANY = M.COMPANY AND P.CLIENT = M.CLIENT
    WHERE
        A.CURDATETIME >= 'XXXX-XX-XX 07:00'
        AND A.CURDATETIME  < 'YYYY-YY-YY 07:00'
        AND A.MATERIAL = 'MATX'
        AND A.CONFIRMATION = 'CONFX'
		AND M.COMPANY = '01'
		AND P.ISDELETE = 0
)
SELECT 	COUNT(CASE WHEN NOTOKDETAIL = 'IK' THEN 1 END) AS IK,
    COUNT(CASE WHEN NOTOKDETAIL = 'IB' THEN 1 END) AS IB,
    COUNT(CASE WHEN NOTOKDETAIL = 'DK' THEN 1 END) AS DK,
    COUNT(CASE WHEN NOTOKDETAIL = 'DB' THEN 1 END) AS DB FROM KMR_DATA;
