WITH ShiftData AS (
  SELECT
	MIN(CURDATETIME) AS STARTTIME,
	MAX(CURDATETIME) AS ENDTIME,
	COUNT(CONFIRMATION) AS QUANTITY,
	NOTOKGORSEL,
	 NOTOKOLCUSEL,
    CASE
            WHEN CAST(CURDATETIME AS TIME) >= '07:00' AND CAST(CURDATETIME  AS TIME) < '15:00' THEN 1
            WHEN (CAST(CURDATETIME  AS TIME) >= '15:00' AND CAST(CURDATETIME  AS TIME) < '23:00') THEN 2
            WHEN (CAST(CURDATETIME  AS TIME) >= '23:00' OR CAST(CURDATETIME  AS TIME) < '07:00') THEN 3
      ELSE 3
    END AS SHIFTAYK
  FROM [dbo].[XYZ]
     WHERE CURDATETIME >= '2024-10-17 07:00' AND CURDATETIME < '2024-10-18 07:00'
    AND CONFIRMATION != 0
  GROUP BY
	CURDATETIME,
	NOTOKGORSEL,
	 NOTOKOLCUSEL
)
SELECT 'XYZ' AS MACHINE, ('Vardiya-' + CAST(SHIFTAYK AS VARCHAR)) AS SHIFTAYK  , SUM(QUANTITY) AS QUANTITY

FROM ShiftData GROUP BY SHIFTAYK

