WITH AYK AS (
  SELECT TOP 1 A.CONFIRMATION , A.MATERIAL ,A.OK AS QUANTITY , (A.NOTOKGORSEL+A.NOTOKOLCUSEL) AS NOTOK,A.NOTOKGORSEL,A.NOTOKOLCUSEL,
	 (DATEDIFF(MINUTE, B.STARTTIME,A.CURDATETIME) )AS TOTALTIME ,( (DATEDIFF(MINUTE, B.STARTTIME,A.CURDATETIME) ) - ISNULL(FAIL.FAILURETIME,0) ) AS WORKINGTIME,ISNULL(FAIL.FAILURETIME,0) AS FAILURETIME, B.STARTTIME ,
	 A.CURDATETIME AS ENDTIME,
	 C.LAST_THIRTY
	FROM [dbo].[XYZ]  A
	LEFT JOIN (SELECT TOP 1 MATERIAL,CONFIRMATION,MIN(CURDATETIME) AS STARTTIME FROM [dbo].[XYZ]  WHERE (CURDATETIME) >= (CAST(CAST(CAST(GETDATE() AS DATE) AS VARCHAR) AS DATETIME) + ' 07:00:00')  GROUP BY MATERIAL,CONFIRMATION ORDER BY MIN(CURDATETIME) DESC) B ON A.MATERIAL = B.MATERIAL
		AND A.CONFIRMATION = B.CONFIRMATION
	LEFT JOIN ( SELECT MATERIAL,CONFIRMATION,DATEADD(MINUTE, -30, GETDATE())  AS STARTTIME,COUNT(CONFIRMATION) AS LAST_THIRTY FROM [dbo].[XYZ]  WHERE CURDATETIME >= DATEADD(MINUTE, -30, GETDATE()) GROUP BY MATERIAL, CONFIRMATION) C  ON A.MATERIAL = B.MATERIAL
		AND A.CONFIRMATION = B.CONFIRMATION
	LEFT JOIN (SELECT MATERIAL,CONFIRMATION,PREVCONFIRMATION,
                                 SUM(DIFF) AS FAILURETIME
                                 FROM (
                                              SELECT
                                              LAG(MATERIAL, 1, NULL) OVER (ORDER BY CURDATETIME ASC) AS PREVMATERIAL,
                                              MATERIAL,
                                              CONFIRMATION,
											  LAG(CONFIRMATION, 1, NULL) OVER (ORDER BY CURDATETIME ASC) AS PREVCONFIRMATION,
                                              CURDATETIME,
                                              LAG(CURDATETIME, 1, NULL) OVER (ORDER BY CURDATETIME ASC) AS WORKSTART,
                                              DATEDIFF(MINUTE, LAG(CURDATETIME, 1, NULL) OVER (ORDER BY CURDATETIME ASC), CURDATETIME) AS DIFF
                                              FROM [dbo].[XYZ]
                                              WHERE [ICCAP] > 0 AND CURDATETIME >= (CAST(CAST(CAST(GETDATE() AS DATE) AS VARCHAR) AS DATETIME) + ' 07:00:00')

                                              GROUP BY MATERIAL,CONFIRMATION,CURDATETIME
                                              ) AS TIMEDIFF
                                 WHERE DIFF > 1 AND CONFIRMATION = PREVCONFIRMATION
                                 GROUP BY MATERIAL,CONFIRMATION,PREVCONFIRMATION
		) FAIL ON A.CONFIRMATION = FAIL.CONFIRMATION AND A.MATERIAL = FAIL.MATERIAL
		WHERE A.CONFIRMATION != 0 AND A.CONFIRMATION IS NOT NULL AND (A.CURDATETIME) >= (CAST(CAST(CAST(GETDATE() AS DATE) AS VARCHAR) AS DATETIME) + ' 07:00:00')
		ORDER BY A.CURDATETIME DESC
)
SELECT DISTINCT TOP 1 'XYZ' AS MACHINE,(CAST(CAST(CAST(GETDATE() AS DATE) AS VARCHAR) AS DATETIME) + ' 07:00:00') AS DAYSTART,
	   CASE WHEN (CONF.NAME + ' '+CONF.SURNAME) IS NULL THEN 'YOK' ELSE  (CONF.NAME + ' '+CONF.SURNAME) END AS NAME,P.MATERIAL ,
       P.PRDORDER , SUM(AYK.QUANTITY) AS QUANTITY,SUM(AYK.NOTOK) AS NOTOK,AYK.NOTOKOLCUSEL,AYK.NOTOKGORSEL,(AYK.TOTALTIME - AYK.FAILURETIME ) AS WORKINGTIME , AYK.TOTALTIME, AYK.FAILURETIME,
       (CAST((SUM(AYK.LAST_THIRTY) / 30 ) AS DECIMAL) / 60) AS SANIYE_DENETLENEN,
       CAST((CAST(CAST(SUM(AYK.NOTOK) AS BIGINT) * 1000000 AS DECIMAL(20, 5))/CAST(SUM(AYK.QUANTITY) AS DECIMAL(20, 5))) AS INT) AS PPM,
       (( SUM(AYK.QUANTITY) / (((AYK.TOTALTIME - ( CASE WHEN AYK.FAILURETIME IS NULL THEN 0 ELSE AYK.FAILURETIME END) ) * 1000 ) /  R.MACHINE ))  * (CAST((AYK.TOTALTIME -( CASE WHEN AYK.FAILURETIME IS NULL THEN 0 ELSE AYK.FAILURETIME END) ) AS DECIMAL) / 480) * 100 ) AS  OEE,
       R.MACHINE AS MACHINETIME
       FROM AYK
	   LEFT JOIN [VALFSAN604].[dbo].IASPRDORDER P ON AYK.CONFIRMATION = P.PRDORDER
       LEFT JOIN (SELECT CLIENT,COMPANY, NAME, SURNAME, PERSONELNUM, PRDORDER, POTYPE
                    FROM (
                          SELECT
                                 C.CLIENT,C.COMPANY,H.NAME, H.SURNAME,C.PERSONELNUM, C.PRDORDER,C.POTYPE,
                                 ROW_NUMBER() OVER (PARTITION BY C.PRDORDER ORDER BY C.PERSONELNUM) AS RowNum
                          FROM [VALFSAN604].[dbo].IASPRDCONF C
                          LEFT JOIN [VALFSAN604].[dbo].IASHCMPERS H ON C.CLIENT = H.CLIENT
                                 AND C.PERSONELNUM = H.PERSID
                          WHERE C.WORKCENTER LIKE ('KMR-%') AND H.NAME IS NOT NULL
                                 AND C.OUTPUT > 0
                    ) AS RankedResults
                    WHERE RowNum = 1
                    GROUP BY  CLIENT, COMPANY,  NAME,SURNAME, PERSONELNUM,PRDORDER, POTYPE) CONF ON P.CLIENT = CONF.CLIENT
             AND P.COMPANY = CONF.COMPANY
             AND P.PRDORDER = CONF.PRDORDER
             AND P.POTYPE = CONF.POTYPE
	   LEFT JOIN  (SELECT CLIENT , COMPANY , MATERIAL , MACHINE FROM [VALFSAN604].[dbo].IASROUOPR WHERE COSTCENTER = 'KMR-AYK') R ON P.CLIENT = R.CLIENT AND P.COMPANY = R.COMPANY AND P.MATERIAL = R.MATERIAL
       WHERE P.POTYPE = 'N2' AND AYK.CONFIRMATION IS NOT NULL
       GROUP BY  AYK.CONFIRMATION,(CONF.NAME + ' '+CONF.SURNAME),P.MATERIAL,AYK.TOTALTIME ,AYK.FAILURETIME, P.PRDORDER,R.MACHINE,AYK.NOTOKGORSEL,AYK.NOTOKOLCUSEL



