SELECT IASPRDCONF.WORKCENTER,MATERIAL,IASPRDCONF.OUTPUT,IASPRDCONF.SCRAP,IASPRDCONF.REWORK,WORKSTART,WORKEND FROM IASPRDCONF
LEFT JOIN IASPRDOPR A ON  A.CONFIRMATION = IASPRDCONF.CONFIRMATION
WHERE IASPRDCONF.CREATEDAT BETWEEN  '20231004' AND '20231005'
AND IASPRDCONF.WORKCENTER IN ('F-02')
AND IASPRDCONF.OUTPUT != 0
AND IASPRDCONF.WORKSTART BETWEEN 'xxxx-yy-zz 23:00:00' AND 'aaaa-bb-cc 23:00:00'