SELECT DISTINCT O.MATERIAL,O.COSTCENTER,C.CONFIRMATION,C.CONFIRMPOS,CAST(C.OUTPUT AS INT) AS QTY
	  ,CAST(C.SCRAP AS INT) AS SCRAPQTY,ISNULL(S.STEXT,'') AS SCRAPTEXT,CAST(C.REWORK AS INT) AS REWORKQTY,REWORKKEY,
       F.BREAKDOWN,C.PERSONELNUM,C.WORKCENTER,C.WORKSTART,
       C.WORKEND ,
	   	CASE WHEN CAST(C.WORKEND AS TIME) > '07:03' AND CAST(C.WORKEND AS TIME) < '15:03' THEN 1
		WHEN CAST(C.WORKEND AS TIME) >= '15:03' AND CAST(C.WORKEND AS TIME) < '23:03' THEN 2
		WHEN ((CAST(C.WORKEND AS TIME) > '23:03' AND CAST(C.WORKEND AS TIME) <= '23:59') OR (CAST(C.WORKEND AS TIME) >= '00:00' AND CAST(C.WORKEND AS TIME) <= '07:14')) THEN 3 END AS SHIFT,
	   CASE WHEN C.WORKEND  > (CASE DATENAME(WEEKDAY, GETDATE()) WHEN 'Monday' THEN
					CAST(CAST(DATEADD(DAY,-2,GETDATE()) AS DATE) AS DATETIME) ELSE  CAST(CAST(DATEADD(DAY,0,GETDATE()) AS DATE) AS DATETIME)  END)
	   THEN (CASE WHEN C.WORKCENTER  NOT LIKE 'CNCTO-%' THEN 1 ELSE 0 END) ELSE 0 END AS ISCONT,
	   F.BREAKDOWNSTART,
       CASE WHEN F.BREAKDOWNEND > CAST(CAST(GETDATE() AS DATE) AS DATETIME) THEN CAST(CAST(GETDATE() AS DATE) AS DATETIME) ELSE F.BREAKDOWNEND END AS BREAKDOWNEND,
	   F.FAILURECODE,
       CASE WHEN F.FAILURECODE IS NULL THEN CASE WHEN C.SETUP = 0 THEN 'Uretim' ELSE 'Kurulum' END  ELSE
		  (CASE WHEN X.STEXT LIKE '%ARIZA%'  THEN 'Ariza Durusu'
		  WHEN  (X.STEXT = 'Kalite Onay Bekleme' OR X.STEXT = 'Set-up Ayar') THEN 'Planli Durus'
		  ELSE 'Plansiz Durus' END)
			 END AS CONFTYPE,
       X.STEXT,
	    CAST(CASE WHEN C.SETUP > 0 THEN 0 ELSE   (CASE WHEN (C.WORKINGTIME*60 - C.FAILURETIME/60) < 0 THEN 0 ELSE (C.WORKINGTIME*60 - C.FAILURETIME/60)  END) END AS INT) AS RUNTIME ,CAST(C.WORKINGTIME *60 AS INT) AS TOTALTIME,
		CASE WHEN C.SETUP > 0 THEN C.WORKINGTIME*60  ELSE  C.FAILURETIME/60 END AS TOTFAILURETIME,
		F.FAILURETIME/60 AS FAILURETIME,

		CAST(CASE WHEN C.SETUP > 0 THEN C.WORKINGTIME*60 ELSE 0 END AS INT) AS SETUPTIME,
	   CASE WHEN R.MACHINE IS NULL THEN R2.MACHINE ELSE R.MACHINE END AS MACHINE,
	   CASE WHEN R.SETUP IS NULL THEN R2.SETUP ELSE R.SETUP END AS SETUP,CAST((CASE WHEN R.MACHINE IS NULL THEN R2.MACHINE ELSE R.MACHINE END)*C.OUTPUT AS DECIMAL)  AS  IDEALCYCLETIME
		,CASE WHEN (R.MACHINE IS NULL AND R2.MACHINE IS NULL) THEN 1 ELSE 0 END AS BADDATA_FLAG
		,P.DISPLAY

FROM IASPRDCONF C
LEFT JOIN  IASPRDFAILURE F ON C.CONFIRMATION  = F.CONFIRMATION
AND C.CONFIRMPOS  = F.CONFIRMPOS
LEFT JOIN IASPRDOPR O ON O.PRDORDER = C.PRDORDER
AND O.CONFIRMATION = C.CONFIRMATION
LEFT JOIN IASCAPWRKCTR R ON O.MATERIAL = R.MATERIAL AND C.WORKCENTER = R.WORKCENTER AND  R.CAPGRPPRIORITY = 1 AND R.CAPGRP IN ('CNC-FREZE','TASLAMA','CNCTO')
LEFT JOIN IASROUOPR R2 ON O.MATERIAL = R2.MATERIAL AND C.WORKCENTER = R2.WORKCENTER AND  O.OPRCONTROL != 'FO' AND O.OPERATION = R2.OPERATION
LEFT JOIN IASPRD005X X ON F.FAILURECODE = X.FAILURECODE AND X.CLIENT = '00' AND X.PLANT = '01' AND X.COMPANY = '01'
LEFT JOIN IASPRD004X S ON C.SCRAPKEY = S.SCRAPKEY
LEFT JOIN IASHCMPER P ON P.PERSID = C.PERSONELNUM
WHERE C.WORKSTART > (CASE DATENAME(WEEKDAY, GETDATE()) WHEN 'Monday' THEN
<<<<<<< HEAD
CAST(CAST(DATEADD(DAY,-3,GETDATE()) AS DATE) AS DATETIME) ELSE  CAST(CAST(DATEADD(DAY,-3,GETDATE()) AS DATE) AS DATETIME)  END)
AND C.WORKSTART < (CASE DATENAME(WEEKDAY, GETDATE()) WHEN 'Monday' THEN
CAST(CAST(DATEADD(DAY,-2,GETDATE()) AS DATE) AS DATETIME) ELSE  CAST(CAST(DATEADD(DAY,-2,GETDATE()) AS DATE) AS DATETIME)  END)
AND O.COSTCENTER IN ('CNC','TASLAMA','CNCTORNA')
=======
CAST ( CAST(CAST(DATEADD(DAY,-3,GETDATE()) AS DATE) AS VARCHAR(100)) + ' 23:00:00.000' AS DATETIME)
ELSE  CAST ( CAST(CAST(DATEADD(DAY,-2,GETDATE()) AS DATE) AS VARCHAR(100)) + ' 23:00:00.000' AS DATETIME)  END)

AND C.WORKSTART  < CAST ( CAST(CAST(DATEADD(DAY,-1,GETDATE()) AS DATE) AS VARCHAR(100)) + ' 23:00:00.000' AS DATETIME)

AND O.COSTCENTER IN ('MONTAJ','CNC','TASLAMA','CNCTORNA')
>>>>>>> 8d4b9bec45aecaad068a226a132ce828faaba106
AND C.POTYPE != CASE  O.COSTCENTER WHEN 'TASLAMA' THEN 'N1' ELSE 'ASD' END
AND C.POTYPE != CASE C.WORKCENTER WHEN 'MONTAJ-W' THEN 'ASD' ELSE 'N2' END
AND C.WORKCENTER != 'GORSEL'
AND C.WORKSTART != C.WORKEND
ORDER BY O.COSTCENTER,C.WORKCENTER,C.CONFIRMATION