SELECT  O.MATERIAL,O.COSTCENTER,C.CONFIRMATION,C.CONFIRMPOS,CAST(C.OUTPUT AS INT) AS QTY,CAST(C.SCRAP AS INT) AS SCRAPQTY,SCRAPKEY,CAST(C.REWORK AS INT) AS REWORKQTY,REWORKKEY,
       F.BREAKDOWN,C.PERSONELNUM,C.WORKCENTER,C.WORKSTART,

       CASE WHEN C.WORKEND  > 'aaaa-bb-cc 23:00:00' THEN  'aaaa-bb-cc 23:00:00' ELSE C.WORKEND END AS WORKEND , F.BREAKDOWNSTART,

       CASE WHEN F.BREAKDOWNEND > 'aaaa-bb-cc 23:00:00' THEN 'aaaa-bb-cc 23:00:00'  ELSE F.BREAKDOWNEND END AS BREAKDOWNEND  ,F.FAILURECODE,
       CASE WHEN F.FAILURECODE IS NULL THEN CASE WHEN C.SETUP = 0 THEN 'PROD' ELSE 'SETUP' END  ELSE 'BREAKDOWN' END AS CONFTYPE,
       X.STEXT,
	    CAST(CASE WHEN C.SETUP > 0 THEN 0 ELSE   (CASE WHEN (C.WORKINGTIME*60 - C.FAILURETIME/60) < 0 THEN 0 ELSE (C.WORKINGTIME*60 - C.FAILURETIME/60)  END) END AS INT) AS RUNTIME ,CAST(C.WORKINGTIME *60 AS INT) AS TOTALTIME,
		CASE WHEN C.SETUP > 0 THEN C.WORKINGTIME*60  ELSE  C.FAILURETIME/60 END AS TOTFAILURETIME,
		F.FAILURETIME/60 AS FAILURETIME,
		CAST(CASE WHEN C.SETUP > 0 THEN C.WORKINGTIME*60 ELSE 0 END AS INT) AS SETUPTIME,
	   CASE WHEN R.MACHINE IS NULL THEN R2.MACHINE ELSE R.MACHINE END AS MACHINE,
	   CASE WHEN R.SETUP IS NULL THEN R2.SETUP ELSE R.SETUP END AS SETUP,CAST((CASE WHEN R.MACHINE IS NULL THEN R2.MACHINE ELSE R.MACHINE END)*C.OUTPUT AS DECIMAL)  AS  IDEALCYCLETIME
FROM IASPRDCONF C
LEFT JOIN  IASPRDFAILURE F ON C.CONFIRMATION  = F.CONFIRMATION
AND C.CONFIRMPOS  = F.CONFIRMPOS
LEFT JOIN IASPRDOPR O ON O.PRDORDER = C.PRDORDER
AND O.CONFIRMATION = C.CONFIRMATION
LEFT JOIN IASCAPWRKCTR R ON O.MATERIAL = R.MATERIAL AND C.WORKCENTER = R.WORKCENTER AND  R.CAPGRPPRIORITY = 1
LEFT JOIN IASROUOPR R2 ON O.MATERIAL = R2.MATERIAL AND C.WORKCENTER = R2.WORKCENTER AND  O.OPRCONTROL != 'FO' AND O.OPERATION = R2.OPERATION
LEFT JOIN IASPRD005X X ON F.FAILURECODE = X.FAILURECODE AND X.CLIENT = '00' AND X.PLANT = '01' AND X.COMPANY = '01'
WHERE C.WORKSTART > 'xxxx-yy-zz 23:00:00'
AND C.WORKSTART  < 'aaaa-bb-cc 23:00:00'
AND O.COSTCENTER IN ('CNC','TASLAMA','CNCTORNA')
ORDER BY O.COSTCENTER,C.WORKCENTER,C.CONFIRMATION