SELECT A.CAPGRP AS CAPGRUP,C.STAND,A.*
    FROM VLFPRESCAP A
    LEFT JOIN (SELECT MAX(STAND) AS STAND,WORKCENTER FROM IASWORKCENT
    WHERE COMPANY = '01' GROUP BY WORKCENTER) C ON A.WORKCENTER = C.WORKCENTER
    WHERE A.COSTCENTER != ''
