SELECT DATE,MPOINT,SCODE,OUTPUT,COSTCENTER,INTERVAL FROM VLFENERGY WHERE MPOINT = 'CNC-07' AND  DATE >= '2023-08-29T00:00:00' AND '2023-09-29T00:00:00' > DATE
SELECT '' AS MPOINT,  FORMAT(IASPRDCONF.WORKSTART ,'yyyy-MM-dd') + 'T00:00:00' AS DATE,
CAST(SUM(IASPRDCONF.OUTPUT +IASPRDCONF.SCRAP+IASPRDCONF.REWORK) AS INT) AS QUANTITY,
CONVERT(DECIMAL(10,3),SUM((IASPRDCONF.OUTPUT +IASPRDCONF.SCRAP+IASPRDCONF.REWORK)*B.NETWEIGHT)/1000000) AS TOTALNETWEIGHT,
0.000 AS kwhPERton
FROM IASPRDCONF
LEFT JOIN IASPRDOPR A ON  A.CONFIRMATION = IASPRDCONF.CONFIRMATION
LEFT JOIN IASMATBASIC B ON A.MATERIAL = B.MATERIAL AND B.COMPANY  = '01'
WHERE IASPRDCONF.WORKCENTER IN ('CNC-07')
AND IASPRDCONF.WORKSTART BETWEEN  '2023-08-29' AND '2023-09-29'
GROUP BY FORMAT(IASPRDCONF.WORKSTART,'yyyy-MM-dd') + 'T00:00:00'