WITH ShiftData AS (
  SELECT
    MACHINE AS MACHINEAYK,
    MATERIAL,
    CONFIRMATION,
    WORKSTART,
    WORKEND,
    TOTALMIN,
    CASE
      WHEN CAST(WORKEND AS TIME) >= '07:00' AND CAST(WORKEND AS TIME) < '15:00' THEN 1
      WHEN (CAST(WORKEND AS TIME) >= '15:00' AND CAST(WORKEND AS TIME) <= '23:00') THEN 2
      ELSE 3
    END AS SHIFTAYK,
    TYPE
  FROM VLFAYKWORKINGTIMES
)
SELECT
  CAST(MIN(WORKSTART) AS DATE) AS MACHINEDATE,
  MACHINEAYK,
  SHIFTAYK,
  MIN(WORKSTART) AS MIN_WORKSTART,
  MAX(WORKEND) AS MAX_WORKEND,
  MATERIAL,
  CONFIRMATION,
  TOTALMIN,
  TYPE
FROM ShiftData
WHERE MATERIAL IS NOT NULL
 AND  WORKSTART BETWEEN 'XXXX-XX-XX' AND 'YYYY-YY-YY'
GROUP BY
  MACHINEAYK,
  SHIFTAYK,
  MATERIAL,
  CONFIRMATION,
  TOTALMIN,
  TYPE
ORDER BY MACHINEAYK, MIN_WORKSTART, SHIFTAYK;