
SELECT
  CAST(MIN(WORKSTART) AS DATE) AS MACHINEDATE,
  MACHINE,
  WORKSTART AS MIN_WORKSTART,
  WORKEND AS MAX_WORKEND,
  MATERIAL,
  CONFIRMATION,
  TOTALMIN,
  TYPE
FROM VLFAYKWORKINGTIMES
WHERE MATERIAL IS NOT NULL
 AND  WORKSTART BETWEEN 'XXXX-XX-XX' AND 'YYYY-YY-YY'
GROUP BY
  MACHINE,
  MATERIAL,
  WORKSTART,
  WORKEND,
  CONFIRMATION,
  TOTALMIN,
  TYPE
ORDER BY MACHINE,WORKSTART;