WITH ShiftData AS (
  SELECT
    MACHINE AS MACHINEAYK,
    MATERIAL,
    CONFIRMATION,
    WORKSTART,
    WORKEND,
    TOTALMIN,
    CASE
      WHEN CAST(WORKEND AS TIME) > '07:00' AND CAST(WORKEND AS TIME) < '15:00' THEN 1
      WHEN (CAST(WORKEND AS TIME) >= '15:00' AND CAST(WORKEND AS TIME) <= '23:00') THEN 2
      ELSE 3
    END AS SHIFTAYK,
    TYPE
  FROM VLFAYKWORKINGTIMES
  WHERE TOTALMIN > 0
)
SELECT
  CAST(MIN(WORKSTART) AS DATE)  AS MACHINEDATE,
  MACHINEAYK,
  SHIFTAYK,
  MIN(WORKSTART) AS MIN_WORKSTART,
  MAX(WORKEND) AS MAX_WORKEND,
  MATERIAL,
  CONFIRMATION,
  SUM(CASE WHEN TYPE = 'CALISIYOR' THEN TOTALMIN ELSE 0 END) AS 'CALISIYOR',
  SUM(CASE WHEN (TYPE = 'BEKLEME DURUSU' OR TYPE = 'MALZEME DURUSU')  THEN TOTALMIN ELSE 0 END) AS 'DURUS',
  (( SUM(CASE WHEN TYPE = 'CALISIYOR' THEN TOTALMIN ELSE 0 END)) - (SUM(CASE WHEN (TYPE = 'BEKLEME DURUSU' OR TYPE = 'MALZEME DURUSU')  THEN TOTALMIN ELSE 0 END))) AS FARK,
  SUM(CASE WHEN TYPE = 'BEKLEME DURUSU' THEN TOTALMIN ELSE 0 END) AS 'BEKLEME_DURUSU',
  SUM(CASE WHEN TYPE = 'MALZEME DURUSU' THEN TOTALMIN ELSE 0 END) AS 'MALZEME_DURUSU'
FROM ShiftData
WHERE MATERIAL IS NOT NULL
  AND MACHINEAYK = 'XYZ' AND  WORKSTART >= 'XXXX-XX-XX 07:00' AND WORKSTART < 'YYYY-YY-YY 07:00'
GROUP BY
  MACHINEAYK,
  SHIFTAYK,
  MATERIAL,
  CONFIRMATION
ORDER BY MACHINEAYK, MIN_WORKSTART, SHIFTAYK;