
SELECT DISTINCT 'XYZ' AS MACHINE,AYK.AYKDATE,AYK.SHIFT AS SHIFTURETIM,(CONF.NAME + ' '+CONF.SURNAME) AS NAME,P.MATERIAL ,
	 P.PRDORDER , SUM(AYK.QUANTITY) AS QUANTITY,SUM(AYK.NOTOK) AS NOTOK,
	0 AS SANIYE_DENETLENEN,
	CAST((CAST(CAST(SUM(AYK.NOTOK) AS BIGINT) * 1000000 AS DECIMAL(20, 5))/CAST(SUM(AYK.QUANTITY) AS DECIMAL(20, 5))) AS INT) AS PPM
	FROM [VALFSAN604].[dbo].IASPRDORDER P
	LEFT JOIN (SELECT CLIENT,COMPANY, NAME, SURNAME, PERSONELNUM, PRDORDER, POTYPE
			FROM (
				SELECT
					C.CLIENT,C.COMPANY,H.NAME, H.SURNAME,C.PERSONELNUM, C.PRDORDER,C.POTYPE,
					ROW_NUMBER() OVER (PARTITION BY C.PRDORDER ORDER BY C.PERSONELNUM) AS RowNum
				FROM [VALFSAN604].[dbo].IASPRDCONF C
				LEFT JOIN [VALFSAN604].[dbo].IASHCMPERS H ON C.CLIENT = H.CLIENT
					AND C.PERSONELNUM = H.PERSID
				WHERE C.WORKCENTER LIKE ('KMR-%') AND H.NAME IS NOT NULL
					AND C.OUTPUT > 0
			) AS RankedResults
			WHERE RowNum = 1
			GROUP BY  CLIENT, COMPANY,  NAME,SURNAME, PERSONELNUM,PRDORDER, POTYPE) CONF ON P.CLIENT = CONF.CLIENT
		AND P.COMPANY = CONF.COMPANY
		AND P.PRDORDER = CONF.PRDORDER
		AND P.POTYPE = CONF.POTYPE
	LEFT JOIN (		SELECT
	T.AYKDATE, T.SHIFT, T.CONFIRMATION,SUM(T.QUANTITY) AS QUANTITY,MAX(T.NOTOK) AS NOTOK
FROM (
    SELECT
	CAST(CURDATETIME AS DATE)  AS AYKDATE,
        CASE
            WHEN CAST(CURDATETIME AS TIME) >= '07:00' AND CAST(CURDATETIME AS TIME) < '15:00' THEN 1
            WHEN (CAST(CURDATETIME AS TIME) >= '15:00' AND CAST(CURDATETIME AS TIME) <= '23:00') THEN 2
            WHEN (CAST(CURDATETIME AS TIME) >= '23:00' OR CAST(CURDATETIME AS TIME) < '07:00') THEN 3
        END AS SHIFT,
        CONFIRMATION,
        CURDATETIME,
        COUNT(CONFIRMATION) AS QUANTITY,
        (MAX([NOTOKGORSEL]) + MAX([NOTOKOLCUSEL])) AS NOTOK
    FROM [dbo].[XYZ]
    WHERE CURDATETIME BETWEEN 'XXXX-XX-XX' AND 'YYYY-YY-YY'
    AND CONFIRMATION != 0
    GROUP BY CONFIRMATION, CURDATETIME
) AS T
GROUP BY T.SHIFT, T.CONFIRMATION,T.AYKDATE
) AYK ON CONF.PRDORDER = AYK.CONFIRMATION
		WHERE P.POTYPE = 'N2'
		AND AYK.CONFIRMATION IS NOT NULL
		GROUP BY  AYK.AYKDATE,AYK.SHIFT,(CONF.NAME + ' '+CONF.SURNAME),P.MATERIAL ,
	 P.PRDORDER ;


