SELECT CASE WHEN B.WORKCENTER LIKE 'T-%' THEN 'TAMBUR'
		 WHEN B.WORKCENTER LIKE 'OTEC%' THEN 'YUZEYISLEM'
			ELSE 'VIBRATORLER' END AS COSTCENTER,B.WORKCENTER, B.STARTDATE,DATEADD(MINUTE,C.MACHINE,B.STARTDATE) AS  FULLNAME, B.STATUS,
       A.MATERIAL AS DRAWNUM,CASE WHEN

				CAST(DATEDIFF(MINUTE,GETDATE(),DATEADD(MINUTE,C.MACHINE,B.STARTDATE))/60.0 AS DECIMAL(10,2)) > 0
			THEN CAST(ABS(CAST(DATEDIFF(MINUTE,GETDATE(),DATEADD(MINUTE,C.MACHINE,B.STARTDATE))/60.0 AS DECIMAL(10,2))) AS varchar(MAX))
			+ ' SAAT SONRA HAZIR'
			ELSE CAST(ABS(CAST(DATEDIFF(MINUTE,GETDATE(),DATEADD(MINUTE,C.MACHINE,B.STARTDATE))/60.0 AS DECIMAL(10,2))) AS varchar(MAX))
			+ ' SAAT GECIKTI' END AS STEXT,
CASE WHEN DATEADD(MINUTE,C.MACHINE,B.STARTDATE) <  GETDATE()  THEN 'brown' ELSE
   ( CASE WHEN B.STATUS = 1 THEN 'Gainsboro'
    WHEN B.STATUS = 2 THEN 'blue'
    WHEN B.STATUS = 3 THEN 'purple'
    WHEN B.STATUS = 4 THEN 'GreenYellow'
    WHEN B.STATUS IN (5,6) THEN 'red'
    WHEN B.STATUS = 6 THEN 'darkred' END ) END AS STATUSR
	FROM IASAUTSTATUS B
	LEFT OUTER JOIN IASPRDOPR A ON A.COMPANY = B.COMPANY
		AND A.CLIENT = B.CLIENT
		AND A.CONFIRMATION = B.CONFIRMATION
	LEFT OUTER JOIN IASROUOPR C ON A.COMPANY = C.COMPANY
		AND A.CLIENT = C.CLIENT
		AND A.MATERIAL = C.MATERIAL
		AND A.OPERATION = C.OPERATION
	LEFT JOIN IASWORKCENT F
	ON F.WORKCENTER = B.WORKCENTER
	WHERE B.CLIENT = '00'
		AND B.COMPANY = '01'
	  	AND F.STAND = 'YUZEYISLEM'
ORDER BY COSTCENTER