SELECT MATERIAL AS MATGRP2,COMPONENT,CATEGORY,PRICE,QTY,[3],[4],[5] -- Replace these years with the actual year values relevant to your data
FROM
(
    SELECT MATERIAL,COMPONENT, PMONTH, ROWBALANCE,CATEGORY,
	MAX(PPRICE) AS PRICE,CAST( MAX(QTY/QUANTITY) AS DECIMAL(10,3) ) AS QTY
    FROM VLFCOMPONENT
    WHERE PMONTH > MONTH(DATEADD(MONTH, -3, GETDATE())) AND
		PYEAR = YEAR(DATEADD(MONTH, -3, GETDATE()))
		AND MATERIAL = 'XXX'
	GROUP BY MATERIAL,COMPONENT, PMONTH, ROWBALANCE,CATEGORY,QUANTITY

) AS SourceTable
PIVOT
(
    SUM(ROWBALANCE)
    FOR PMONTH IN ([3],[4],[5])  -- This should match the years in the SELECT clause
) AS PivotTable;
